[package]
name = "urfri"
version = "0.1.0"
authors = ["lzszone <lzszone@gmail.com>"]

[dependencies]
actix-web = "0.7.4"
diesel = {version ="1.3.3", features = ["postgres"]}
dotenv = "0.13.0"
ring = "0.13.2"